- composer.json
- composer.lock
We should be able to finally update code sniffer repos for our splits.
> Update code sniffer.

- composer.json
- composer.lock
> Remove outdated ComposerAdjuster hook.

- composer.json
- composer.lock
> Clean dependencies.

- config/Shared/config_default_AT.php
- src/Pyz/Client/RabbitMq/RabbitMqConfig.php
Fix default mode for rabbit-mq
> Fix issues regarding rabbit-mq default mode

- .travis.yml
- composer.json
- composer.lock
- data/import/glossary.csv
> Merge nonsplit master

- tslint.json
Ticket: https://spryker.atlassian.net/browse/TE-4281
Fix after release: https://release.spryker.com/release-groups/view/1959
> TE-4281: Fixed tslint validation issue.

- config/Shared/config_default-docker.php
- deploy.dev.yml
- Ticket: https://spryker.atlassian.net/browse/SC-2092
- Introduced a new `Swagger UI` service for the Docker environment.
> Feature/sc 2092/master swagger

- .travis.yml
> Test md run

- .travis.yml
- config/install/docker.yml
- deploy.ci.yml
- tests/PyzTest/Glue/Products/RestApi/ProductAbstractRestApiCest.php
- tests/PyzTest/Glue/Products/RestApi/ProductConcreteRestApiCest.php
- Ticket: https://spryker.atlassian.net/browse/SC-2197
- Docker SDK PR: https://github.com/spryker/docker-sdk/pull/44
- Release Group: https://release.spryker.com/release-groups/view/2017
- Adjust Travis performance for Docker. Execution per store and reduced operation steps, e.g assets building.
> SC-2256: Travis CI single store

- deploy.dev.yml
- Ticket: https://spryker.atlassian.net/browse/SC-2287
- Introduced a new Kibana service for Docker Environment.
- Introduced a new TCP ElasticSearch server configuration.
- Introduced a new TCP RabbitMq server configuration.
> SC-2287: Expose ES and RabbitMq ports. New Kibana service.

- .travis.yml
- composer.json
- composer.lock
> Increase php version for travis

- composer.lock
- src/Pyz/Yves/ShopApplication/YvesBootstrap.php
Overview
- RG: 2105
- Ticket: https://spryker.atlassian.net/browse/TE-4505
> TE-4505 Removed usage of deprecated ServiceProvider.

- composer.json
- composer.lock
- Ticket: https://spryker.atlassian.net/browse/CC-7049
> CC-7049: Added spryker/category-gui module

- config/Shared/config_default-docker.php
- config/install/docker.yml
- src/Pyz/Yves/Form/FormDependencyProvider.php
- src/Pyz/Yves/ShopApplication/ShopApplicationDependencyProvider.php
- src/Pyz/Yves/Twig/TwigDependencyProvider.php
- src/Pyz/Zed/Application/ApplicationDependencyProvider.php
- src/Pyz/Zed/Form/FormDependencyProvider.php
- src/Pyz/Zed/Twig/TwigDependencyProvider.php
- Ticket: https://spryker.atlassian.net/browse/SC-1983
Core PRs
- URL_HERE
> SC-1983: Docker. Prod-like images

- deploy.ci.yml
- deploy.dev.yml
- deploy.yml
- Ticket: https://spryker.atlassian.net/browse/SC-2733
- Introduced a mechanism to handle composer parameters in the Docker environment
> SC-2733: Docker composer arguments

- .known_hosts
- Ticket: https://spryker.atlassian.net/browse/SC-2566
- Added `known-hosts.yml` for providing hosts into containers
> SC-2566: ssh known hosts should be updated with ssh GitHub com command

- .travis.yml
- Ticket: https://spryker.atlassian.net/browse/SC-2894
- RG: 
- Debian as base image
> SC-2894: Use Debian as base image

- composer.json
Same as on non-split side again
> Revert a bad merge resolution.

- composer.json
- composer.lock
- Ticket: https://spryker.atlassian.net/browse/TE-4708
> PHPStan 0.12 upgrade

- .travis.yml
- Ticket: https://spryker.atlassian.net/browse/TE-5899
resolves some of the merge issues (dropped changes).
> Activate psalm for suite

- src/Pyz/Zed/Console/ConsoleDependencyProvider.php
Follow https://github.com/spryker-shop/suite/pull/511
> Fixed wrong merge

- composer.lock
- src/Pyz/Zed/Collector/CollectorConfig.php
- src/Pyz/Zed/Touch/TouchConfig.php
- RG: 2752
- Ticket: https://spryker.atlassian.net/browse/TE-5605
> TE-5605 nonsplit to split merge

- .travis.yml
- Ticket: https://spryker.atlassian.net/browse/SC-3951
- Enables Travis's job for prod assets compilation.
- Enables Travis's job for MariaDB check.
> SC-3951: Travis jobs for prod assets generation and MariaDB check

- README.md
- Ticket: https://spryker.atlassian.net/browse/SC-4083
> README.md contains popular use cases and docker-sdk usage

- composer.json
> TE-7001 Removed require-dev devependency.

- .github/workflows/marketplace.yml
- .github/workflows/validation.yml
- .travis.yml
- Ticket: https://spryker.atlassian.net/browse/TE-7918
Partially replaced Travis with GitHub Actions.
> TE-7918 Added GA workflows as partial replacement for Travis

- README.md
> Adjust badge

- .editorconfig
- composer.json
- composer.lock
> Fix up psalm upgrade.

- tests/PyzTest/Glue/UpSellingProducts/RestApi/CartUpSellingProductsRestApiCest.php
- tests/PyzTest/Glue/UpSellingProducts/RestApi/CartUpSellingProductsRestApiFixtures.php
- tests/PyzTest/Glue/UpSellingProducts/RestApi/GuestCartUpSellingProductsRestApiCest.php
- tests/PyzTest/Glue/UpSellingProducts/RestApi/GuestCartUpSellingProductsRestApiFixtures.php
Reverts spryker-shop/suite#780
> Revert "Bugfix/supesc 175 404page does not support mgetcache fix"

- .github/workflows/ci.yml
- angular.json
- frontend/merchant-portal/entry-points.js
- frontend/merchant-portal/mp-paths.js
- package-lock.json
- package.json
- tsconfig.json
- tsconfig.mp.json
- yarn.lock
Enable MP tests and build in GA validation job.
_NOTE:_ Merge together with https://github.com/spryker/spryker/pull/8141
> CI: Add MP tests and build to validation job

- composer.json
- composer.lock
> Sync and fix up dependencies

- composer.json
- composer.lock
Also cleaned up a few unnecessary dependency constraints.
https://spryker.atlassian.net/browse/TE-5922
> TE-5922 Use PHPUnit9 for split

- tests/PyzTest/Zed/AclEntity/Persistence/AclDirector/RelationHandlingTest.php
- tests/PyzTest/Zed/AclEntity/Persistence/AclDirector/SegmentScopeAclQueryDirectorStrategyTest.php
- Ticket: https://spryker.atlassian.net/browse/MP-5449
> MP-5449 merged with nonsplit to resolve conflicts.

- .github/workflows/ci.yml
> Revert for now

- .github/workflows/ci.yml
Maybe replaced by https://github.com/spryker-shop/suite/pull/944
> Use PHP 8 stable.

- composer.lock
- src/Pyz/Zed/DocumentationGeneratorRestApi/DocumentationGeneratorRestApiConfig.php
Complete https://github.com/spryker-shop/suite/pull/941
- Ticket: https://spryker.atlassian.net/browse/TE-10415
Core PRs
- https://github.com/spryker/spryker/pull/8985
> TE-10415 adjusted config to be consistent with GlueApplication state.

- composer.json
- composer.lock
It also needs
- https://github.com/spryker-sdk/composer-constrainer/releases/tag/0.2.6
- https://github.com/spryker-sdk/spryk-gui/releases/tag/0.2.2
> TE-10992 Upgrade suite to PHPStan 1.5.x

- composer.json
- composer.lock
- Ticket: https://spryker.atlassian.net/browse/CC-16720
> CC-16720 remove spryker/code-it-now from dependency

- composer.lock
- phpcs.xml
> For slevomat cs v8+

- composer-overwrite.yml
- composer.json
- composer.lock
Removed old symfony console and security-core constraints in root composer.json
> Removed old symfony console and security-core constraints in root composer.json

- .github/workflows/ci.yml
- composer.json
To make sure we dont declare untestable/unusable min versions (majors only).
> Check prefer lowest

- .github/workflows/ci.yml
- composer.json
- composer.lock
- Cleanup composer json
- Updated GH Action CI
> Cleanup composer.json and updated GH-Action ci.yml to use latest ubuntu, latest docker compose V2 and last possible (according license) ES 7.x

- composer.lock
- phpcs.xml
> Fix up PHPCS config

- frontend/merchant-portal/tsconfig.spec.json
- Ticket: https://spryker.atlassian.net/browse/CC-21271
Core PRs
- URL_HERE
> CC-21271 updated suite/frontend/merchant-portal/tsconfig.spec.json

- .github/workflows/ci.yml
Ticket: https://spryker.atlassian.net/browse/CC-26329
> CC-26329 Updated GitHub Actions to use Node.js 16.

- .github/workflows/ci.yml
- Ticket: https://spryker.atlassian.net/browse/CC-26250
> CC-26250 Enabled Robot framework tests.

- .github/workflows/ci.yml
- Ticket:  https://spryker.atlassian.net/browse/FRW-6858
> FRW-6858 adjusted CI to terminate builds for outdated commits.

- .github/workflows/ci.yml
- Ticket: https://spryker.atlassian.net/browse/CC-32022
> CC-32022 Updated robot tests.

- .github/workflows/ci.yml
FRW-7397 added new job for api dynamic multistore
- Ticket: [https://spryker.atlassian.net/browse/FRW-7397]
> FRW-7397 added new job for api dynamic multistore

- deploy.ci.acceptance.mariadb.dynamic-store.robot.yml
СС-33164 added configurator settings into yml file
- Ticket: [https://spryker.atlassian.net/browse/CC-33164]
> СС-33164 added configurator settings into yml file

- package-lock.json
- package.json
**Overview**
- https://spryker.atlassian.net/browse/CC-33850
> CC-33850: ws frontend dependency issue

- dependency-overview.json
- Ticket: -
Core PRs
- None
Quarterly update of dependency overview. The overview has no impact on any behaviour, it contains statistical data only.
> Dependency Overview update on 28 June 2024

- src/Pyz/Zed/ZedNavigation/ZedNavigationConfig.php
- Ticket: https://spryker.atlassian.net/browse/CC-34310
> CC-34310 Added missing constants

- src/Pyz/Zed/DataImport/Business/Model/ProductAbstract/ProductAbstractHydratorStep.php
- Ticket: https://spryker.atlassian.net/browse/CC-34258
> CC-34258: Fixed data-import step to support multiselect product attributes.

- deploy.ci.acceptance.yml
- Ticket: https://spryker.atlassian.net/browse/FRW-7213
> FRW-7213 Fixed CI.

- dependency-overview.json
- Ticket: https://spryker.atlassian.net/issues/AE-57
> AE-57 Quarterly update of Dependency Overview

- deploy.dynamic-store-off.yml
- Ticket: https://spryker.atlassian.net/browse/FRW-9118
> FRW-9118 Fixed deployment file.

- composer.lock
- Ticket: https://spryker.atlassian.net/browse/CC-34810
Core PRs
- URL_HERE
> CC-34501: Fixed REST api schema.

- package-lock.json
- package.json
- tsconfig.mp.json
- Ticket: https://spryker.atlassian.net/browse/FRW-9454
> FRW-9454 Update cross-spawn dependency

- deploy.ci.acceptance.mariadb.dynamic-store-off.robot.yml
- Ticket: https://spryker.atlassian.net/browse/FRW-9464
> FRW-9464 Disabled debug mode. 

- dependency-overview.json
- Ticket: https://spryker.atlassian.net/browse/AE-57
Updating FOSS list.
> AE-57 2025 Q1 FOSS list update

- .github/workflows/ci.yml
- Ticket: https://spryker.atlassian.net/browse/FRW-9711
> FRW-9444 Trigger jobs PR on unlabeled.

- .github/actions/scheduled-job-slack-notifications/action.yml
- .github/workflows/ci.yml
- Ticket: https://spryker.atlassian.net/browse/FRW-9607
Adjustments
- Updated `ci.yml` and `robot-ui-e2e-tests.yml` to run workflows weekly on schedule.
- If the workflow was run by schedule the system sends notifications about execution status in Slack.
> FRW-9607: Automate Weekly CI Test Execution

- composer.json
> Temporary bump platform version

- data/import/common/common/glossary.csv
- Ticket: https://spryker.atlassian.net/browse/SSP-829
> SSP-829 Added missing translation.

- composer.json
- composer.lock
- Ticket: https://spryker.atlassian.net/browse/FRW-10118
Core PRs
- https://github.com/spryker-sdk/evaluator/pull/72
Updated evaluator to ignore feature-ui in version checks
> FRW-10118 Updated evaluator version.

- composer.json
> Update composer.json to enable release after SSP release

- tests/PyzTest/Zed/ProductOption/Business/ProductOptionFacadeAggregatorTest.php
> CC-35509: trigger ci

- .github/workflows/ci.yml
> trigger ci

- composer.json
- composer.lock
Removed deprecated module.
```
DISCOURAGED PACKAGES CHECKER
============================
+---+-----------------------------------------+-------------------------------------------------------------+
| # | Message                                 | Target                                                      |
+---+-----------------------------------------+-------------------------------------------------------------+
| 1 | The package is not recommended anymore. | spryker/price-product-offer-sales-order-amendment-connector |
+---+-----------------------------------------+-------------------------------------------------------------+
```
> Removed deprecated module from composer.

- dependency-overview.json
- Ticket: https://spryker.atlassian.net/browse/SSP-1532
Core PRs
Tests do **not** run automatically on every PR.
To trigger the required test suites, please add the appropriate label(s) to your PR.
For the full list of labels and their associated tests, see our Confluence page: [CI Test Labels & Triggers](https://spryker.atlassian.net/wiki/spaces/Framework/pages/4715216905/Using+PR+labels+to+control+CI+runs+for+project+repositories)
> SSP-1532: Added FOSS support for the SSP.

- composer.lock
Core PRs
- https://spryker.atlassian.net/browse/CC-36474
Tests do **not** run automatically on every PR.
To trigger the required test suites, please add the appropriate label(s) to your PR.
For the full list of labels and their associated tests, see our Confluence page: [CI Test Labels & Triggers](https://spryker.atlassian.net/wiki/spaces/Framework/pages/4715216905/Using+PR+labels+to+control+CI+runs+for+project+repositories)
> CC-36474: fixed Merchant databuilders
